Fix Twilio SMS function missing React dependencies
- Added react and react-dom dependencies to twilio-serverless package.json
- Fixes Error: Cannot find module 'react-dom/server' when using Resend
- Redeployed function successfully to fabsy-twilio-sms-email-2693-dev.twil.io
- SMS forwarding should now work properly